### ISSUE TITLE
amazon button

### ISSUE THREAD

**Issue by puchrojo** [dufferzafar/Userscripts#2]
Hi,
I can't find the import button in amazon. Maybe you can give one or two url as example. To check if it work. 

I try with this two:
http://www.amazon.com/gp/product/B00MIA0L9U/
http://www.amazon.es/De-Paris-Transilvania-Lucas-Masciano/dp/B00NXRGUY2/

Regards,
Isaac

**Comment by dufferzafar** [comment]
Closing because I don't use the Amazon importer myself and don't plan to update it.
